
<div id="app"></div>



<?php
//$this->headScript()->appendScript($this->partial('zf-metal/calendar/vue-apps/ticket-schedule-simple/dist/build.js'), 'text/javascript')
?>


<?php
$this->headScript()
    ->appendScript($this->partial('zf-metal/calendar/vue-apps/ticket-schedule/dist/static/js/manifest.2ae2e69a05c33dfc65f8.js'), 'text/javascript')
    ->appendScript($this->partial('zf-metal/calendar/vue-apps/ticket-schedule/dist/static/js/vendor.625b8ebb5e7fc8e764bb.js'), 'text/javascript')
    ->appendScript($this->partial('zf-metal/calendar/vue-apps/ticket-schedule/dist/static/js/app.6ee3bb3203559455c530.js'), 'text/javascript')
?>
