<?php
$form = $this->form;
$form->prepare();
$elementsReady = array();
?>

<?php echo $this->form()->openTag($form); ?>


<?php echo $this->renderFormElement($form->get('id')); ?>
<?php echo $this->renderFormElement($form->get('name')); ?>

<?php //echo $this->formCollection($form->get(1)); ?>
<?php //echo $this->formCollection($form->get(2)); ?>
<?php //echo $this->formCollection($form->get(3)); ?>
<?php //echo $this->formCollection($form->get(4)); ?>
<?php //echo $this->formCollection($form->get(5)); ?>
<?php //echo $this->formCollection($form->get(6)); ?>
<?php //echo $this->formCollection($form->get(7)); ?>
<?php //echo $this->formCollection($form->get(8)); ?>

<?php echo $this->formCollection($form->get("schedules")); ?>

<?php echo $this->renderFormElement($form->get('submit')); ?>

<?php echo $this->form()->closeTag($form); ?>
